// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheGate.Infrastructure.Persistence;

#nullable disable

namespace TheGate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20261007011207_AddTradeOperations")]
    partial class AddTradeOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.ComplianceTaskRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequirementSource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ResponsibleOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TradeRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeRecordId");

                    b.ToTable("ComplianceTasks", t =>
                        {
                            t.HasCheckConstraint("CK_ComplianceTasks_Status", "\"Status\" IN ('Required', 'EvidenceRecorded', 'ResponsiblePartyAttested') AND ((\"Status\" = 'Required' AND \"EvidenceReference\" IS NULL) OR (\"Status\" IN ('EvidenceRecorded', 'ResponsiblePartyAttested') AND \"EvidenceReference\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.DirectTradeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AgreedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset?>("BuyerClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BuyerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiatedByOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProducerClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProducerConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProducerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerOrganizationId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ProducerOrganizationId");

                    b.ToTable("DirectTradeRecords", t =>
                        {
                            t.HasCheckConstraint("CK_DirectTradeRecords_Status", "\"Status\" IN ('AwaitingProducerConfirmation', 'Confirmed', 'Closed') AND ((\"Status\" = 'AwaitingProducerConfirmation' AND \"ProducerConfirmedAtUtc\" IS NULL) OR (\"Status\" IN ('Confirmed', 'Closed') AND \"ProducerConfirmedAtUtc\" IS NOT NULL)) AND ((\"Status\" = 'Closed' AND \"ProducerClosedAtUtc\" IS NOT NULL AND \"BuyerClosedAtUtc\" IS NOT NULL) OR (\"Status\" <> 'Closed' AND NOT (\"ProducerClosedAtUtc\" IS NOT NULL AND \"BuyerClosedAtUtc\" IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.LogisticsMilestoneRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportedByOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId", "Type")
                        .IsUnique();

                    b.ToTable("LogisticsMilestones");
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.LogisticsShipmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LastMilestone")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResponsibleProviderOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipmentReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TradeRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeRecordId", "ShipmentReference")
                        .IsUnique();

                    b.ToTable("LogisticsShipments", t =>
                        {
                            t.HasCheckConstraint("CK_LogisticsShipments_LastMilestone", "\"LastMilestone\" >= 0 AND \"LastMilestone\" <= 10");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.PaymentObligationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BeneficiaryOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("PartnerReportedSettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PayerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentPartnerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TradeRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeRecordId");

                    b.ToTable("PaymentObligations", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentObligations_Status", "\"Amount\" > 0 AND \"Status\" IN ('Pending', 'PartnerReportedSettled') AND ((\"Status\" = 'Pending' AND \"PartnerReportedSettledAtUtc\" IS NULL) OR (\"Status\" = 'PartnerReportedSettled' AND \"PartnerReportedSettledAtUtc\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.ProductOfferRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("DeclaredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("ExternalContactUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("MinimumDirectTradeQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ProducerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProducerOrganizationId");

                    b.ToTable("ProductOffers", t =>
                        {
                            t.HasCheckConstraint("CK_ProductOffers_Quantity", "CAST(\"DeclaredQuantity\" AS NUMERIC) > 0 AND CAST(\"MinimumDirectTradeQuantity\" AS NUMERIC) > 0 AND CAST(\"MinimumDirectTradeQuantity\" AS NUMERIC) <= CAST(\"DeclaredQuantity\" AS NUMERIC) AND CAST(\"AllocatedQuantity\" AS NUMERIC) >= 0 AND CAST(\"AllocatedQuantity\" AS NUMERIC) <= CAST(\"DeclaredQuantity\" AS NUMERIC)");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.VerificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("InspectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MeasuredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("TradeRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("VerifierOrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeRecordId");

                    b.ToTable("VerificationReports");
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.ComplianceTaskRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.DirectTradeRow", null)
                        .WithMany()
                        .HasForeignKey("TradeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.DirectTradeRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.ProductOfferRow", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.LogisticsMilestoneRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.LogisticsShipmentRow", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.LogisticsShipmentRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.DirectTradeRow", null)
                        .WithMany()
                        .HasForeignKey("TradeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.PaymentObligationRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.DirectTradeRow", null)
                        .WithMany()
                        .HasForeignKey("TradeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.VerificationRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.DirectTradeRow", null)
                        .WithMany()
                        .HasForeignKey("TradeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
