// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheGate.Infrastructure.Persistence;

#nullable disable

namespace TheGate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    partial class TradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.DirectTradeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AgreedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("BuyerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiatedByOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProducerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerOrganizationId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ProducerOrganizationId");

                    b.ToTable("DirectTradeRecords");
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.ProductOfferRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("DeclaredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("ExternalContactUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("MinimumDirectTradeQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ProducerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProducerOrganizationId");

                    b.ToTable("ProductOffers", t =>
                        {
                            t.HasCheckConstraint("CK_ProductOffers_Quantity", "CAST(\"DeclaredQuantity\" AS NUMERIC) > 0 AND CAST(\"MinimumDirectTradeQuantity\" AS NUMERIC) > 0 AND CAST(\"MinimumDirectTradeQuantity\" AS NUMERIC) <= CAST(\"DeclaredQuantity\" AS NUMERIC) AND CAST(\"AllocatedQuantity\" AS NUMERIC) >= 0 AND CAST(\"AllocatedQuantity\" AS NUMERIC) <= CAST(\"DeclaredQuantity\" AS NUMERIC)");
                        });
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.VerificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("InspectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MeasuredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("TradeRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("VerifierOrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeRecordId");

                    b.ToTable("VerificationReports");
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.DirectTradeRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.ProductOfferRow", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGate.Infrastructure.Persistence.VerificationRow", b =>
                {
                    b.HasOne("TheGate.Infrastructure.Persistence.DirectTradeRow", null)
                        .WithMany()
                        .HasForeignKey("TradeRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
